Repository xoopscube/xcl, pull requests merged in 2019-10, with the labels that each got.

#110 Merge branch Develop
  html/class/xoopsmailer.php
  html/common/elfinder/README.md
  html/common/elfinder/css/elfinder.full.css
  html/common/elfinder/css/elfinder.min.css
  html/common/elfinder/css/theme.css
  html/common/elfinder/js/commands/edit.js
  html/common/elfinder/js/commands/netmount.js
  html/common/elfinder/js/commands/paste.js
  html/common/elfinder/js/commands/quicklook.plugins.js
  html/common/elfinder/js/elFinder.js
  html/common/elfinder/js/elFinder.options.js
  html/common/elfinder/js/elFinder.resources.js
  html/common/elfinder/js/elFinder.version.js
  html/common/elfinder/js/elfinder.full.js
  html/common/elfinder/js/elfinder.min.js
  html/common/elfinder/js/extras/editors.default.js
  html/common/elfinder/js/extras/editors.default.min.js
  html/common/elfinder/js/i18n/elfinder.LANG.js
  html/common/elfinder/js/i18n/elfinder.cs.js
  html/common/elfinder/js/i18n/elfinder.en.js
  html/common/elfinder/js/i18n/elfinder.fr.js
  html/common/elfinder/js/i18n/elfinder.it.js
  html/common/elfinder/js/i18n/elfinder.ja.js
  html/common/elfinder/js/i18n/elfinder.nl.js
  html/common/elfinder/js/i18n/elfinder.pl.js
  html/common/elfinder/js/i18n/elfinder.ru.js
  html/common/elfinder/js/i18n/elfinder.sk.js
  html/common/elfinder/js/i18n/elfinder.zh_CN.js
  html/common/elfinder/js/ui/cwd.js
  html/common/elfinder/js/ui/dialog.js
  html/common/elfinder/js/ui/navbar.js
  html/common/elfinder/js/ui/searchbutton.js
  html/install/include/makedata.php
  html/install/language/english/finish.php
  html/install/language/english/install.php
  html/install/language/english/welcome.php
  html/install/sql/mysql.structure.sql
  html/install/sql/upgrade/mysql.structure.sql
  html/install/wizards/install_insertData.inc.php
  html/install/wizards/install_langselect.inc.php
  html/install/wizards/install_updateConfig_go.inc.php
  html/modules/legacy/admin/actions/BlockInstallListAction.class.php
  html/modules/legacy/language/english/help/abc_1st.html
  html/modules/legacy/language/english/help/abc_2nd.html
  html/modules/legacy/language/english/help/abc_3rd.html
  html/modules/legacy/language/english/help/xoops2.html
  html/modules/legacy/language/english/modinfo.php
  html/modules/legacyRender/language/english/admin.php
  html/modules/stdCache/admin/index.php
  html/modules/stdCache/language/english/help/help.html
  html/modules/stdCache/language/english/modinfo.php
  html/modules/xelfinder/cache/elfzdledzc8E
  html/modules/xelfinder/include/js/xelfinderUiOptions.default.js
  html/themes/legacy_default/theme.html
Labels: enhancement

#111 Sync branches
  html/class/criteria.php
  html/class/module.textsanitizer.php
  html/class/token.php
  html/class/xoopscomments.php
  html/core/XCube_Utils.class.php
  html/core/libs/IniHandler.class.php
  html/kernel/avatar.php
  html/kernel/comment.php
  html/kernel/config.php
  html/kernel/configcategory.php
  html/kernel/configitem.php
  html/kernel/configoption.php
  html/kernel/group.php
  html/kernel/groupperm.php
  html/kernel/image.php
  html/kernel/imagecategory.php
  html/kernel/imageset.php
  html/kernel/imagesetimg.php
  html/kernel/module.php
  html/kernel/notification.php
  html/kernel/object.php
  html/kernel/privmessage.php
  html/kernel/tplfile.php
  html/kernel/tplset.php
  html/modules/legacy/class/comment.php
  html/modules/legacy/class/non_installation_module.php
  html/modules/legacy/kernel/handler.php
  html/modules/legacy/kernel/object.php
  html/modules/message/class/handler/Inbox.class.php
  html/modules/message/class/handler/Outbox.class.php
  html/modules/message/class/handler/Settings.class.php
Labels: enhancement

#113 Update Changelog
  CHANGELOG.md
Labels: enhancement

#119 MultiToken to be not inherited class.
  html/class/token.php
Labels: bug

#122 Fixed multi token hander
  html/class/token.php
Labels: bug

#123 remove get_magic_quotes_gpc() and cleanup arounds (#121)
  html/class/module.textsanitizer.php
  html/class/uploader.php
  html/core/XCube_ActionForm.class.php
  html/core/XCube_HttpContext.class.php
  html/install/class/textsanitizer.php
  xoops_trust_path/libs/altsys/include/gtickets.php
  xoops_trust_path/modules/d3forum/class/gtickets.php
  xoops_trust_path/modules/pico/class/FormProcessByHtml.class.php
  xoops_trust_path/modules/pico/class/PicoExtraFields.class.php
  xoops_trust_path/modules/pico/class/gtickets.php
  xoops_trust_path/modules/protector/class/gtickets.php
  xoops_trust_path/modules/protector/class/protector.php
Labels: bug, enhancement

#155 #135 static callback
  html/modules/legacy/preload/Primary/SiteClose.class.php
Labels: bug
